name: Pull Request Review Notification

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Pull Request Details
        id: pr_details
        run: |
          echo "::set-output name=title::${{ github.event.pull_request.title }}"
          echo "::set-output name=description::${{ github.event.pull_request.body }}"

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_SECRET }}
        with:
          channel: "Korab Duklini"
          status: "SUCCESS"
          text: |
            :warning: Pull Request Review Requested :warning:

            *Repository*: ${{ github.repository }}
            *Pull Request*: ${{ github.event.pull_request.html_url }}
            *Author*: ${{ github.event.pull_request.user.login }}
            *Title*: ${{ steps.pr_details.outputs.title }}
            *Description*: ${{ steps.pr_details.outputs.description }}
